{pkgs}: {
  deps = [
    pkgs.logrotate
    pkgs.tor
    pkgs.trufflehog
    pkgs.gitleaks
    pkgs.coturn
    pkgs.gdk-pixbuf
    pkgs.libglvnd
    pkgs.x264
    pkgs.vulkan-loader
    pkgs.nghttp2
    pkgs.libpsl
    pkgs.wayland
    pkgs.libmanette
    pkgs.graphene
    pkgs.gtk4
    pkgs.gcc-unwrapped
    pkgs.flite
    pkgs.libjpeg_turbo
    pkgs.libjpeg8
    pkgs.harfbuzz
    pkgs.libtiff
    pkgs.libheif
    pkgs.libavif
    pkgs.lcms2
    pkgs.libevent
    pkgs.zlib
    pkgs.brotli
    pkgs.openssl
    pkgs.libvorbis
    pkgs.libtheora
    pkgs.libopus
    pkgs.libvpx
    pkgs.flac
    pkgs.libjpeg
    pkgs.libpng
    pkgs.freetype
    pkgs.fontconfig
    pkgs.sqlite
    pkgs.libffi
    pkgs.libgpg-error
    pkgs.libgcrypt
    pkgs.p11-kit
    pkgs.gnutls
    pkgs.libtasn1
    pkgs.libxslt
    pkgs.libxml2
    pkgs.icu74
    pkgs.openjpeg
    pkgs.libsecret
    pkgs.libnotify
    pkgs.libgudev
    pkgs.libGL
    pkgs.libepoxy
    pkgs.harfbuzzFull
    pkgs.icu
    pkgs.hyphen
    pkgs.enchant2
    pkgs.woff2
    pkgs.libwebp
    pkgs.libsoup_3
    pkgs.gst_all_1.gst-libav
    pkgs.gst_all_1.gst-plugins-bad
    pkgs.gst_all_1.gst-plugins-good
    pkgs.gst_all_1.gst-plugins-base
    pkgs.gst_all_1.gstreamer
    pkgs.libgbm
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libxcb
    pkgs.xorg.libX11
    pkgs.systemd
    pkgs.glib
    pkgs.dbus
    pkgs.expat
    pkgs.libxkbcommon
    pkgs.alsa-lib
    pkgs.cairo
    pkgs.pango
    pkgs.gtk3
    pkgs.mesa
    pkgs.libdrm
    pkgs.cups
    pkgs.at-spi2-core
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.nginx
  ];
}
