// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/compare-bullets/Hybrid.tsx": () => import("../components/mockups/compare-bullets/Hybrid.tsx"),
  "./components/mockups/hero-variants/Comparison.tsx": () => import("../components/mockups/hero-variants/Comparison.tsx"),
  "./components/mockups/hero-variants/Comparison2.tsx": () => import("../components/mockups/hero-variants/Comparison2.tsx"),
  "./components/mockups/hero-variants/IterationA.tsx": () => import("../components/mockups/hero-variants/IterationA.tsx"),
  "./components/mockups/hero-variants/IterationB.tsx": () => import("../components/mockups/hero-variants/IterationB.tsx"),
  "./components/mockups/hero-variants/Variant01.tsx": () => import("../components/mockups/hero-variants/Variant01.tsx"),
  "./components/mockups/hero-variants/Variant02.tsx": () => import("../components/mockups/hero-variants/Variant02.tsx"),
  "./components/mockups/hero-variants/Variant03.tsx": () => import("../components/mockups/hero-variants/Variant03.tsx"),
  "./components/mockups/hero-variants/Variant04.tsx": () => import("../components/mockups/hero-variants/Variant04.tsx"),
  "./components/mockups/hero-variants/Variant05.tsx": () => import("../components/mockups/hero-variants/Variant05.tsx"),
  "./components/mockups/pricing-bullets/Hybrid.tsx": () => import("../components/mockups/pricing-bullets/Hybrid.tsx"),
  "./components/mockups/spec-line/Variants.tsx": () => import("../components/mockups/spec-line/Variants.tsx"),
  "./components/mockups/threat-model-bullets/Hybrid.tsx": () => import("../components/mockups/threat-model-bullets/Hybrid.tsx"),
  "./components/mockups/transformer-morph/HorizontalTransition.tsx": () => import("../components/mockups/transformer-morph/HorizontalTransition.tsx"),
  "./components/mockups/transformer-morph/VerticalTransition.tsx": () => import("../components/mockups/transformer-morph/VerticalTransition.tsx"),
  "./components/mockups/landing-redesign/Brutalista.tsx": () => import("../components/mockups/landing-redesign/Brutalista.tsx"),
  "./components/mockups/landing-redesign/Current.tsx": () => import("../components/mockups/landing-redesign/Current.tsx"),
  "./components/mockups/landing-redesign/Retrofuture.tsx": () => import("../components/mockups/landing-redesign/Retrofuture.tsx"),
  "./components/mockups/sife-themes/BoneWhite.tsx": () => import("../components/mockups/sife-themes/BoneWhite.tsx"),
  "./components/mockups/sife-themes/BrutalistaForm.tsx": () => import("../components/mockups/sife-themes/BrutalistaForm.tsx"),
  "./components/mockups/sife-themes/GoldVoyager.tsx": () => import("../components/mockups/sife-themes/GoldVoyager.tsx"),
  "./components/mockups/sife-themes/RetroFuturist.tsx": () => import("../components/mockups/sife-themes/RetroFuturist.tsx"),
  "./components/mockups/why-bullets/Bulleted.tsx": () => import("../components/mockups/why-bullets/Bulleted.tsx"),
  "./components/mockups/why-bullets/Hybrid.tsx": () => import("../components/mockups/why-bullets/Hybrid.tsx"),
  "./components/mockups/why-bullets/Vonnegut.tsx": () => import("../components/mockups/why-bullets/Vonnegut.tsx")
};
